import type { AlertEntry } from "@shared/schema";
import { userHasPermission } from "../auth";
import type { User } from "@shared/schema";
import { storage } from "../storage";

interface EmailConfig {
  apiKey: string;
  from: string;
  to: string;
}

function getEmailConfig(): EmailConfig | null {
  const apiKey = process.env.RESEND_API_KEY;
  const from = process.env.ALERT_EMAIL_FROM;
  const to = process.env.ALERT_EMAIL_TO;

  if (!apiKey || !from || !to) {
    return null;
  }

  return { apiKey, from, to };
}

const MAX_EMAIL_RETRIES = 3;
const EMAIL_RETRY_DELAY_MS = 1000;

async function sendEmailWithRetry(
  config: EmailConfig,
  subject: string,
  body: string,
  retryCount = 0,
): Promise<boolean> {
  try {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 10000);

    const res = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${config.apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from: config.from,
        to: config.to.split(",").map((v) => v.trim()).filter(Boolean),
        subject,
        text: body,
      }),
      signal: controller.signal,
    });

    clearTimeout(timeout);

    if (res.ok) {
      console.log("Alert email sent successfully");
      return true;
    }

    if (res.status >= 500 && retryCount < MAX_EMAIL_RETRIES) {
      console.warn(`Email API error ${res.status}, retrying (attempt ${retryCount + 1}/${MAX_EMAIL_RETRIES})`);
      await new Promise((resolve) => setTimeout(resolve, EMAIL_RETRY_DELAY_MS * (retryCount + 1)));
      return sendEmailWithRetry(config, subject, body, retryCount + 1);
    }

    const text = await res.text();
    console.error(`Failed to send alert email after ${retryCount + 1} attempts: ${res.status} ${text}`);
    return false;
  } catch (error) {
    if (retryCount < MAX_EMAIL_RETRIES) {
      console.warn(`Email send failed: ${error instanceof Error ? error.message : String(error)}, retrying...`);
      await new Promise((resolve) => setTimeout(resolve, EMAIL_RETRY_DELAY_MS * (retryCount + 1)));
      return sendEmailWithRetry(config, subject, body, retryCount + 1);
    }

    console.error(`Failed to send alert email after retries: ${error instanceof Error ? error.message : String(error)}`);
    return false;
  }
}

export async function sendHighRiskAlertEmail(
  alert: AlertEntry,
  userRole?: string,
  userId?: string,
): Promise<boolean> {
  console.log(`[Email] Attempting to send alert email for ${alert.cveId}. User: ${userId}, Role: ${userRole}`);

  // Check permission to send alert emails
  if (userRole && userId) {
    const hasPermission = userHasPermission({ role: userRole } as User, "send_alert_email");
    console.log(`[Email] Permission check for ${userId}: ${hasPermission ? "GRANTED" : "DENIED"}`);

    if (!hasPermission) {
      console.warn(`User ${userId} lacks permission to send alert emails for CVE ${alert.cveId}`);
      // Log denial to audit trail
      await storage.addAuditLog({
        action: "alert_email_denied",
        user: userId,
        details: `Insufficient permissions to send email for high-risk alert (CVE: ${alert.cveId})`,
        category: "alert",
      });
      return false;
    }
  } else {
    console.log(`[Email] No user context provided, skipping permission check`);
  }

  const config = getEmailConfig();
  if (!config) {
    console.warn(
      "Email configuration is incomplete. Skipping alert email. Set RESEND_API_KEY, ALERT_EMAIL_FROM, and ALERT_EMAIL_TO.",
    );
    return false;
  }
  console.log(`[Email] Config found. Sending to: ${config.to}`);

  const subject = `[CTAM] High-Risk Vulnerability Detected: ${alert.cveId}`;

  const body = [
    `A new high-risk alert has been generated by CTAM (Cyber Threat Analysis and Mitigation System).`,
    "",
    `CVE ID: ${alert.cveId}`,
    `Risk Level: ${alert.riskLevel}`,
    `Confidence: ${(alert.probability * 100).toFixed(1)}%`,
    `Status: ${alert.status}`,
    `Triggered By: ${alert.triggeredBy}`,
    "",
    "Mitigation Summary:",
    alert.mitigation,
    "",
    "Please login to the CTAM dashboard for full details and remediation steps.",
  ].join("\n");

  return sendEmailWithRetry(config, subject, body);
}

